#!/usr/bin/env python3
"""Rasterize Baloo 2 ExtraBold glyphs for task labels."""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
FONT_PATH = ROOT / "assets" / "fonts" / "Baloo2-Variable.ttf"
OUTPUT = ROOT / "task_font.h"
FIRST = 32
LAST = 126
CELL_WIDTH = 16
CELL_HEIGHT = 24
FONT_SIZE = 26


def glyph_bitmap(font, character):
    source = Image.new("L", (96, 96), 0)
    draw = ImageDraw.Draw(source)
    draw.text((48, 48), character, font=font, fill=255, anchor="mm")
    bbox = source.getbbox()
    if not bbox:
        return [[0] * CELL_WIDTH for _ in range(CELL_HEIGHT)]

    glyph = source.crop(bbox)
    scale = min((CELL_WIDTH - 2) / glyph.width, (CELL_HEIGHT - 2) / glyph.height)
    size = (max(1, round(glyph.width * scale)), max(1, round(glyph.height * scale)))
    glyph = glyph.resize(size, Image.Resampling.LANCZOS)
    canvas = Image.new("L", (CELL_WIDTH, CELL_HEIGHT), 0)
    canvas.paste(glyph, ((CELL_WIDTH - size[0]) // 2, (CELL_HEIGHT - size[1]) // 2))
    return [list(canvas.crop((0, row, CELL_WIDTH, row + 1)).getdata())
            for row in range(CELL_HEIGHT)]


def main():
    font = ImageFont.truetype(FONT_PATH, FONT_SIZE)
    font.set_variation_by_name("ExtraBold")
    glyphs = [glyph_bitmap(font, chr(code)) for code in range(FIRST, LAST + 1)]

    with OUTPUT.open("w", encoding="utf-8", newline="\n") as output:
        output.write("/* Generated by tools/make_task_font.py from Baloo 2 ExtraBold. */\n")
        output.write("#ifndef BALLOON_TASKS_FONT_H\n#define BALLOON_TASKS_FONT_H\n\n")
        output.write("#include <stdint.h>\n\n")
        output.write(f"#define TASK_GLYPH_WIDTH {CELL_WIDTH}\n")
        output.write(f"#define TASK_GLYPH_HEIGHT {CELL_HEIGHT}\n\n")
        output.write("static const uint8_t task_font_bitmap[95][TASK_GLYPH_HEIGHT][TASK_GLYPH_WIDTH] = {\n")
        for glyph in glyphs:
            output.write("    {\n")
            for row in glyph:
                output.write("        {" + ", ".join(str(pixel) for pixel in row) + "},\n")
            output.write("    },\n")
        output.write("};\n\n#endif\n")


if __name__ == "__main__":
    main()
