#!/usr/bin/env python3
"""Rasterize Baloo 2 ExtraBold glyphs for task text.

Each face keeps the font's own advances and baseline, so "i" stays narrow
and "p" hangs below the line. Glyph coverage is stored once in a shared
pixel pool; each glyph records where its ink sits relative to the pen:

    pen ---> +--------- advance ---------+
             |   x,y +---+               |
    ascent   |       |ink| h             |
    baseline +-------+---+---------------+
                       w
"""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
FONT_PATH = ROOT / "assets" / "fonts" / "Baloo2-Variable.ttf"
OUTPUT = ROOT / "task_font.h"
FIRST = 32
LAST = 126

# Pixel sizes: SMALL for hints, NORMAL for tasks, LARGE for the pressed close button.
FACES = [("SMALL", 15), ("NORMAL", 26), ("LARGE", 44)]


def rasterize(font, character):
    left, top, right, bottom = font.getbbox(character, anchor="ls")
    advance = round(font.getlength(character))
    width = right - left
    height = bottom - top
    if width <= 0 or height <= 0:
        return advance, 0, 0, 0, 0, []

    image = Image.new("L", (width, height), 0)
    ImageDraw.Draw(image).text((-left, -top), character, font=font, fill=255, anchor="ls")
    return advance, left, top, width, height, list(image.getdata())


def main():
    pool = []
    faces = []
    for name, size in FACES:
        font = ImageFont.truetype(FONT_PATH, size)
        font.set_variation_by_name("ExtraBold")
        glyphs = []
        for code in range(FIRST, LAST + 1):
            advance, x, y, w, h, pixels = rasterize(font, chr(code))
            glyphs.append((advance, x, y, w, h, len(pool)))
            pool.extend(pixels)

        # The font's own ascent leaves room for accents ASCII never uses.
        ascent = max(-y for _, _, y, _, h, _ in glyphs if h)
        descent = max(y + h for _, _, y, _, h, _ in glyphs if h)
        faces.append((name, ascent, ascent + descent, glyphs))

    with OUTPUT.open("w", encoding="utf-8", newline="\n") as output:
        output.write("/* Generated by tools/make_task_font.py from Baloo 2 ExtraBold. */\n")
        output.write("#ifndef BALLOON_TASKS_FONT_H\n#define BALLOON_TASKS_FONT_H\n\n")
        output.write("#include <stdint.h>\n\n")
        output.write(f"#define TASK_FONT_FIRST {FIRST}\n")
        output.write(f"#define TASK_FONT_GLYPHS {LAST - FIRST + 1}\n\n")
        output.write("typedef struct {\n"
                     "    int16_t advance;\n"
                     "    int16_t x, y;\n"
                     "    uint16_t w, h;\n"
                     "    uint32_t offset;\n"
                     "} TaskGlyph;\n\n")
        output.write("typedef struct {\n"
                     "    int ascent;\n"
                     "    int line_height;\n"
                     "    TaskGlyph glyphs[TASK_FONT_GLYPHS];\n"
                     "} TaskFace;\n\n")
        output.write("enum TaskFaceSize {\n")
        for name, _, _, _ in faces:
            output.write(f"    TASK_FACE_{name},\n")
        output.write("    TASK_FACE_COUNT\n};\n\n")
        output.write("static const TaskFace task_faces[TASK_FACE_COUNT] = {\n")
        for name, ascent, line_height, glyphs in faces:
            output.write(f"    [TASK_FACE_{name}] = {{\n        {ascent}, {line_height}, {{\n")
            for advance, x, y, w, h, offset in glyphs:
                output.write(f"            {{{advance}, {x}, {y}, {w}, {h}, {offset}}},\n")
            output.write("        }\n    },\n")
        output.write("};\n\n")
        output.write(f"static const uint8_t task_font_pixels[{len(pool)}] = {{\n")
        for start in range(0, len(pool), 24):
            output.write("    " + ", ".join(str(p) for p in pool[start:start + 24]) + ",\n")
        output.write("};\n\n#endif\n")


if __name__ == "__main__":
    main()
